resources:
  - name: source-code
    type: git
    source:
      uri: git@github.com:BradleyCulley/concourse.git
      private_key: ((concourse-repo-private-key))
  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:BradleyCulley/concourse.git
      branch: version
      file: version
      private_key: ((concourse-repo-private-key))

jobs:
  - name: version-bump
    plan:
      - get: source-code
        trigger: true
      - get: version
        params: {bump: minor}
      - put: version
        params: {file: version/version}
  - name: example-job
    plan:
      - get: source-code
        trigger: true
      - get: version
        passed: [version-bump]
        trigger: true
      - task: print-hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world]
      - task: display-version
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: version
          run:
            path: cat
            args: [version/number]
